### PR TITLE
fix(ChromoteSession): `$view()` tries old inspector path first

### LINKED ISSUE #224: View error,  but headless still working
It seems to be working headlessly, but I can't figure out how to get a browser window or tab. I have 10 "Google Chrome for Testing" processes running. When I click on the chrome.exe it runs fine. I used the Run window (as suggested in the vignette) to run the chrome, and that worked fine.  I've also tried with my antivirus off.  Any help would be appreciated.

``` r
library(chromote)

chrome_versions_list()
#>             version revision       binary platform
#> 18270 135.0.7049.84  1427262       chrome    win64
#> 18275 135.0.7049.84  1427262 chromedriver    win64
#>                                                                                                       url
#> 18270       https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/win64/chrome-win64.zip
#> 18275 https://storage.googleapis.com/chrome-for-testing-public/135.0.7049.84/win64/chromedriver-win64.zip
#>                                                                                                           path
#> 18270             C:/Users/tbats/AppData/Local/R/cache/R/chromote/chrome/135.0.7049.84/chrome-win64/chrome.exe
#> 18275 C:/Users/tbats/AppData/Local/R/cache/R/chromote/chrome/135.0.7049.84/chromedriver-win64/chromedriver.exe
chrome_versions_path()
#> [1] "C:/Users/tbats/AppData/Local/R/cache/R/chromote/chrome/135.0.7049.84/chrome-win64/chrome.exe"
get_chrome_args()
#> [1] "--disable-gpu"              "--force-color-profile=srgb"
#> [3] "--disable-extensions"       "--mute-audio"

b <- ChromoteSession$new()
b$view()
#> Error in chromote$url(path): path must be NULL or a string that starts with "/"
b$go_to("https://www.google.com")
#> Error: attempt to apply non-function
b$Page$navigate("https://www.google.com")
#> $frameId
#> [1] "3228DBE388E7F9F9E214E81578392D6F"
#> 
#> $loaderId
#> [1] "840D48179998EB38010B57193994D2CD"

Sys.sleep(3)

tmppngfile <- tempfile(fileext = ".png")
is_interactive <- interactive() # Display screenshot if interactive
b$screenshot(tmppngfile, show = is_interactive)
#> [1] "C:\\Users\\tbats\\AppData\\Local\\Temp\\RtmpQLA1N2\\file2d9067d34d1.png"
```

<sup>Created on 2025-04-08 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<Details>

<Summary>Session Info</Summary>

``` r
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.2 (2024-10-31 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/New_York
 date     2025-04-08
 rstudio  2024.12.1+563 Kousa Dogwood (desktop)
 pandoc   3.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 callr         3.7.6   2024-03-25 [1] RSPM
 chromote    * 0.5.0   2025-03-21 [1] RSPM (R 4.4.0)
 cli           3.6.4   2025-02-13 [1] RSPM
 clipr         0.8.0   2022-02-22 [1] RSPM
 digest        0.6.37  2024-08-19 [1] RSPM
 evaluate      1.0.3   2025-01-10 [1] RSPM (R 4.4.0)
 fastmap       1.2.0   2024-05-15 [1] RSPM
 fs            1.6.5   2024-10-30 [1] RSPM
 glue          1.8.0   2024-09-30 [1] RSPM
 htmltools     0.5.8.1 2024-04-04 [1] RSPM
 jsonlite      1.8.9   2024-09-20 [1] RSPM
 knitr         1.49    2024-11-08 [1] RSPM
 later         1.4.1   2024-11-27 [1] RSPM
 lifecycle     1.0.4   2023-11-07 [1] CRAN (R 4.4.2)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.4.2)
 pillar        1.10.1  2025-01-07 [1] RSPM (R 4.4.0)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.4.2)
 processx      3.8.5   2025-01-08 [1] RSPM (R 4.4.0)
 promises      1.3.2   2024-11-28 [1] RSPM
 ps            1.8.1   2024-10-28 [1] RSPM
 R6            2.6.1   2025-02-15 [1] RSPM (R 4.4.0)
 Rcpp          1.0.14  2025-01-12 [1] CRAN (R 4.4.2)
 reprex        2.1.1   2024-07-06 [1] RSPM
 rlang         1.1.5   2025-01-17 [1] RSPM (R 4.4.0)
 rmarkdown     2.29    2024-11-04 [1] RSPM
 rstudioapi    0.17.1  2024-10-22 [1] CRAN (R 4.4.2)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.4.2)
 tibble        3.2.1   2023-03-20 [1] RSPM
 vctrs         0.6.5   2023-12-01 [1] RSPM
 websocket     1.4.2   2024-07-22 [1] RSPM (R 4.4.0)
 withr         3.0.2   2024-10-28 [1] RSPM
 xfun          0.50    2025-01-07 [1] RSPM (R 4.4.0)
 yaml          2.3.10  2024-07-26 [1] RSPM

 [1] C:/Users/tbats/AppData/Local/R/win-library/4.4
 [2] C:/Program Files/R/R-4.4.2/library

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

<\Details>

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #224, stacks on #225

The `$view()` method now composes and tries the older `/devtools/inspector.html` path rather than using the fully-qualified chrome-devtools-frontend.appspot.com URL.

### CODE REVIEW

File: R/chromote_session.R [hunk 1]
```diff
@@ -204,10 +204,31 @@ ChromoteSession <- R6Class(
       # A data frame of targets, one row per target.
       info <- fromJSON(self$parent$url("/json"))
       path <- info$devtoolsFrontendUrl[info$id == private$target_id]
+
       if (length(path) == 0) {
         stop("Target info not found.")
       }
 
+      if (grepl("^https://chrome-devtools-frontend\\.appspot\\.com", path)) {
```
Comment (gadenbuie) [inline R/chromote_session.R:212]: We could also put this behind an option flag, e.g. `chromote.use_legacy_inspector_path` or something similar, that defaults to `TRUE`. That would give an out to anyone who wants to use the new URL or if the `/devtools/inspector.html` path changes or breaks in the future (there are no signs that it would). It would also give us a place to document how to set the `--remote-allow-origins` arg.

File: R/chromote_session.R [hunk 2]
```diff
@@ -204,10 +204,31 @@ ChromoteSession <- R6Class(
...
+        inspector_path <- "/devtools/inspector.html"
+        inspector_contents <- tryCatch(
+          readLines(self$parent$url(inspector_path)),
+          error = function(err) character(0)
+        )
+        if (length(inspector_contents) > 0) {
+          ws_url <- info$webSocketDebuggerUrl[info$id == private$target_id]
+          ws_url <- sub("ws://", "ws=", ws_url)
+          inspector_url <- paste0(inspector_path, "?", ws_url)
+          return(browse_url(inspector_url, self$parent))
```
Comment (wch) [inline R/chromote_session.R:228]: One really tiny nit: I'd slightly prefer doing:

```suggestion
          path <- paste0(inspector_path, "?", ws_url)
```

and then continuing on, so that there's just one place this function return from.

**Review by wch — APPROVED** [review]
Thank you!
