### PR TITLE
Listen the Inspector.targetCrashed event

### LINKED ISSUE #39: Handle Inspector.targetCrashed event?
When running headless Chrome in docker, the target may crash because of insufficient resources. In that case, the [Inspector.targetCrashed](https://chromedevtools.github.io/devtools-protocol/tot/Inspector/#event-targetCrashed) event fires.  

For now, this event has to be handled by the user of chromote. As chromote provides some helper methods to create the target, I wonder whether this event should be supervised by chromote.

### PR DESCRIPTION
**Pull request by RLesur**
This closes #39.

### CODE REVIEW

File: R/chromote.R [hunk 1]
```diff
@@ -302,6 +302,13 @@ Chromote <- R6Class(
         private$sessions[[sid]] <- NULL
         session$mark_closed()
       })
+
+      # When a target crashes, raise a warning.
+      # The session cannot be closed because no session id is returned by the
+      # Inspector.targetCrashed event
+      self$protocol$Inspector$targetCrashed(function(msg) {
+        warning("A target has crashed.")
```
Comment (wch) [inline R/chromote.R:310]: How about:

```suggestion
        warning("Chromote has received a Inspector.targetCrashed event. This means that the Chrome/Chromium process has probably crashed.")
```

Is this message accurate? I don't really know anything about the `Inspector.targetCrashed` event.

Comment (RLesur) [reply R/chromote.R:310]:
```suggestion
        warning("Chromote has received a Inspector.targetCrashed event. This means that the ChromoteSession has probably crashed.")
```
When `Inspector.targetCrashed` fires, the Chrome process still runs, only the target/tab has crashed.

I have got the `Inspector.targetCrashed` event only in docker. In this context, the session has been lost.
Lauching Chrome with the `--disable-dev-shm-usage` flag has always solved the problem, that's why `pagedown::chrome_print()` gives this hint: https://github.com/rstudio/pagedown/blob/f9779e38a4b9652b111fc763c414ea61998cb208/R/chrome.R#L637
